### ISSUE TITLE
[AppShell] Strings of the menu items do not truncate

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2221]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Translated text strings in ui shell menus do not ellipse 

### To Reproduce

Extend the string in any of the menu items and it cuts off. The menu items will do this in some translations.
![image (21)](https://user-images.githubusercontent.com/21066152/114867990-6db9aa80-9dc3-11eb-84ac-3b59f427cdd7.png)

### Specific timeline issues / requests
MAS 8.5

**Comment by JordanWSmith15** [comment]
Guidance is typically to truncate 
https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default

**Comment by kevinsperrine** [comment]
We just need to add a specificity override to the header menu items to force them to be display inline in the menus instead of flex and confirm that doesn't cause any other issues.


// current
```css
.bx--header-action-btn span {
    display: flex;
}
```

// changes
```css
.bx--header-action-btn .bx--header__menu-item span {
    display: inline;
}
```
